version: '3.1'

volumes:
  mongodb:

networks:
  go-api:

services:

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - go-api
    volumes:
      - mongodb:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    depends_on:
      - mongo
    networks:
      - go-api
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongo
